export const HANDLE_LOADING = 'HANDLE_LOADING';

export const HANDLE_FETCH_DATA_SUCCESS = 'HANDLE_FETCH_DATA_SUCCESS';
export const HANDLE_FETCH_DATA_FAILED = 'HANDLE_FETCH_DATA_FAILED';

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const HANDLE_MAX_ITEMS = 'HANDLE_MAX_ITEMS';

export const HANDLE_PAGE_CHANGE = 'HANDLE_PAGE_CHANGE';

export const HANDLE_SEARCH_NAME = 'HANDLE_SEARCH_NAME';

export const HANDLE_DATABASE_SEARCH_SUCCESS = 'HANDLE_DATABASE_SEARCH_SUCCESS';
export const HANDLE_DATABASE_SEARCH_FAILED = 'HANDLE_DATABASE_SEARCH_FAILED';

export const HANDLE_BEER_DETAILS_SUCCESS = 'HANDLE_BEER_DETAILS_SUCCESS';
export const HANDLE_BEER_DETAILS_FAILED = 'HANDLE_BEER_DETAILS_FAILED';
