export const HANDLE_LOADING = 'HANDLE_LOADING';

export const HANDLE_FETCH_DATA_SUCCESS = 'HANDLE_FETCH_DATA_SUCCESS';
export const HANDLE_FETCH_DATA_FAILED = 'HANDLE_FETCH_DATA_FAILED';

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
